#!/bin/bash 

. util

function save_oh_my_zsh() {

}

function save_brew_packages() {
    shout "Saving Brew packages to '.brew' file"

    brew list --formula > .brew 

    fin
}

function download_brew_packages() {
    shout "Downloading Brew packages from `brew` file"

    brew install $(cat brew) 
}

function save_zshrc() {
    shout "Saving .zshrc file"
    cp $HOME/.zshrc .zshrc
    fin
}

function save_aliases() {
    shout "Saving aliases to .alias file"
    alias >> .aliases
}

function save_functions() {
    shout "Saving functions to .functions file"
    functions >> .functions
    fin
}

function save_go_env() {
    shout "Saving Go env"
    
    go env >> .go-env
}